### ISSUE TITLE
panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by mholt** [rogerwelin/cassowary#1]
Running a simple test:

```
$ cassowary run -u http://localhost:2015 -c 10 -n 100000

Starting Load Test with 100000 requests using 10 concurrent users

 100% |████████████████████████████████████████| [3s:0s]            3.000194405s
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
main.calcMedian(0x0, 0x0, 0x0, 0x17800)
	/Users/rogerwelin/programming/cassowary/stats.go:29 +0xd8
main.(*cassowary).coordinate(0xc00001e700, 0xc00001e700, 0xc00014c120)
	/Users/rogerwelin/programming/cassowary/load.go:203 +0xe04
main.validateRun(0xc0000d4c60, 0x0, 0xc000176060)
	/Users/rogerwelin/programming/cassowary/cli.go:76 +0x35c
github.com/urfave/cli.HandleAction(0x1453980, 0x150e5c0, 0xc0000d4c60, 0xc0000d4c60, 0x0)
	/Users/rogerwelin/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:523 +0xbe
github.com/urfave/cli.Command.Run(0x14e9f41, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x14f1292, 0xf, 0x0, ...)
	/Users/rogerwelin/go/pkg/mod/github.com/urfave/cli@v1.22.1/command.go:174 +0x51c
github.com/urfave/cli.(*App).Run(0xc000130380, 0xc00001e100, 0x8, 0x8, 0x0, 0x0)
	/Users/rogerwelin/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:276 +0x718
main.runCLI(0xc00001e100, 0x8, 0x8)
	/Users/rogerwelin/programming/cassowary/cli.go:198 +0x946
main.main()
	/Users/rogerwelin/programming/cassowary/main.go:8 +0x45
```

I'm using this binary on macOS: https://github.com/rogerwelin/cassowary/releases/tag/v0.1.1

**Comment by kataras** [comment]
Hello @rogerwelin, nice project, keep up this awesome work!

Just to help you, on Windows it works as expected, so the issue @mholt  is os-specific.

![image](https://user-images.githubusercontent.com/22900943/72381477-1fc97900-3720-11ea-8d73-9fd4156f6f1e.png)

**Comment by rogerwelin** [comment]
@mholt thanks for reporting the issue. I'm using the same binary on mac but cannot recreate the issue atm. Nonetheless the panic should be handled. I will dig further!

@kataras thanks man, appreciate it! 👍

**Comment by mholt** [comment]
Should be an easy fix; it seems that `calcMedian` doesn't account for slices of len 0. https://github.com/rogerwelin/cassowary/blob/v0.1.1/stats.go#L20-L29

**Comment by kataras** [comment]
You are welcome @rogerwelin, I opened a [new feature request](https://github.com/rogerwelin/cassowary/issues/2) too.

**Comment by rogerwelin** [comment]
@mholt you are very much correct. I've released a new version which fixes this bug, https://github.com/rogerwelin/cassowary/releases/tag/v0.2.0. Big fan of caddy btw!

**Comment by mholt** [comment]
Thanks! That did the trick.
