### ISSUE TITLE
[Package] Homebrew page?

### ISSUE THREAD

**Issue by dalisoft** [rogerwelin/cassowary#19]
Hi @rogerwelin and contributors.

Thanks for such a great work.
It is possible Homebrew package release?
Can you're publish to Homebrew?

**Comment by rogerwelin** [comment]
Hi @dalisoft, thanks for your kind words.
Homebrew packaging is certainly a good idea. I will look into adding it!

**Comment by dalisoft** [comment]
Thanks a lot

**Comment by rogerwelin** [comment]
@dalisoft cassowary has now been added to homebrew, just do the following:

```bash
brew update && brew install cassowary
```

**Comment by dalisoft** [comment]
@rogerwelin Thanks a lot. This makes my workflow easier and better
