### ISSUE TITLE
PATCH support is missing

### ISSUE THREAD

**Issue by rvinfoblox** [rogerwelin/cassowary#23]
Hi, I needed PATCH support similar to POST and I have modified the code in my local machine and it will be useful for others too.  Could you please give me permission to contribute to this open source project with those changes by raising a pull request?  thanks.

**Comment by rogerwelin** [comment]
Hi @rvinfoblox and thanks for the interest in cassowary. Your contribution is welcome and you can do that with a pull request so you don't need permission to cassowary's master branch. You can read here about how to make a pull request: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by rvinfoblox** [comment]
Created https://github.com/rogerwelin/cassowary/pull/24 .
Could you please review and merge if you are good with it?

**Comment by rogerwelin** [comment]
Thanks for the PR! It's been merged, I will draft a new release soon
