### ISSUE TITLE
[Chore Feature Request]: Use cassowary_linux_x86_64.zip instead of cassowary_{VERSION}_Linux_x86_64.tar.gz.zip

### ISSUE THREAD

**Issue by dalisoft** [rogerwelin/cassowary#25]
Hi @rogerwelin and contributors.

Thanks to amazing tool.
I use cassowary and i want integrate downloads as binary, but i can't download LATEST version always, i need modify my ansible playbook to use.
I.e i currently can't download via `https://github.com/rogerwelin/cassowary/releases/latest/download/cassowary_Linux_x86_64.tar.gz`

It is possible change release build binary names to cassowary_Linux_x86_64.tar.gz or something static ?

Thanks again

**Comment by dalisoft** [comment]
Also removing LICENSE and README files from binary build would be helpful for cleaner solution

**Comment by rogerwelin** [comment]
Hi @dalisoft, I'll give input when vacations over :)

**Comment by dalisoft** [comment]
Thanks

**Comment by rogerwelin** [comment]
@dalisoft Fixed! Next release will contain tar ball package name without release version in it meaning you will be able to grab it with latest in url
