### ISSUE TITLE
feature request: more percentiles

### ISSUE THREAD

**Issue by mooreniemi** [rogerwelin/cassowary#32]
I find it's often useful to see the p99/p100 behavior of a system. I think a spread of p90, p99, p100 is more informative than p95 only, though I understand it's nice to have a single metric.

I can see [where in the code to start](https://github.com/rogerwelin/cassowary/blob/d658c938f2b0e8dcea65a1285a5a00b0bd623a97/pkg/client/stats.go#L64), but I am curious if it violates your design tenets. If so it's not worth doing a PR.

What do you think?

**Comment by rogerwelin** [comment]
Hi @mooreniemi, thanks for your interest in the project. Honestly I don't want to take up too much real estate on the screen by adding p90, p95, p99, p100/max. Cassowary can output histogram and boxplot which can visualize that information better.

However it would be useful to add Max/p100 in the result output, like so for example:

Content Transfer................: Avg/mean=3.90ms 	Median=1.50ms   Max=5ms	p(95)=4.00ms

Do you want to take a stab at it?
