### ISSUE TITLE
0.14.0 checksum changed

### ISSUE THREAD

**Issue by iMichka** [rogerwelin/cassowary#38]
Hello. I am one of the maintainers of Homebrew, a package manager for macOS and Linux.

We noticed that the checksum of the 0.14.0 release has changed from:
385232478b8552d56429fbe2584950bfbe42e3b611919a31075366a143aae9a9
to:
04fbf1e563378bc37a5ad44e69a3b100647406ea2debae2d38d3c406399628fa

Did someone re-tag the release (which is [the insane thing to do, see the git manual](https://git-scm.com/docs/git-tag#_discussion), or did someone malicious gain access to your repo?

Tags that change are seen as a major security issue on our side, and we need confirmation that this was only a retag.

In future situations were you need to retag, please create a new tag/release instead.

See https://github.com/Homebrew/homebrew-core/pull/95741 for the issue on our side.

**Comment by rogerwelin** [comment]
Hi. I find this very hard to believe. When is this supposed change in checksum supposed to been changed?
I am the only one that can contribute to the Cassowary repo and my account has MFA enabled. Last release, commit and tag was pushed 12 Mar 2021, hence no recent re-tagging

**Comment by iMichka** [comment]
Ok we found out what happened.

> curl https://github.com/rogerwelin/cassowary/archive/v0.14.0.tar.gz -L
the given path has multiple possibilities: #<Git::Ref:0x00007fd87706cf50>, #<Git::Ref:0x00007fd877072428

Looks like there is a v0.14.0 branch, and it is conflicting with the tag. This makes us pull the wrong tarball url.
We will use the specific https://github.com/rogerwelin/cassowary/archive/refs/tags/v0.14.0.tar.gz long url instead.

Thanks for the feedback.
