### ISSUE TITLE
Feature request: export raw data

### ISSUE THREAD

**Issue by gwerbin** [rogerwelin/cassowary#42]
Thanks for this nice tool!

Is it possible to add an option to export the _raw_ per-request data somehow? The histogram and boxplot are nice, but I'd really like to be able to do my own analysis and generate my own charts. One use case is to generate nice charts in company theme colors, or to perform downstream statistical analysis/modeling, outlier detection, etc.

If exporting the raw data isn't possible, then at least it would be nice to get enough data to generate my own histogram with a separate program (e.g. Gnuplot), maybe just a JSON array of bin locations and counts at each bin.

**Comment by rogerwelin** [comment]
Hi @gwerbin, yes I think that could be accomplished. I'll have to experiment with the output format a bit, but I'm leaning towards a csv file. Would that work for you?

**Comment by gwerbin** [comment]
@rogerwelin CSV would be fine!

**Comment by gwerbin** [comment]
Wow, thanks!!
