### ISSUE TITLE
Is there a way to disable tls verification?

### ISSUE THREAD

**Issue by lakuapik** [rogerwelin/cassowary#48]
Hi, thanks for this great cli app, it's very useful.

I see an option to specify custom `ca` or `cert`, but..

Is there a way to entirely disable tls verification? says for self-signed certificate or invalid certificate hostname.

```
2024/04/05 16:42:10 Get "https://aaa.abc.com": tls: failed to verify certificate: x509: certificate is valid for abc.com, not abc.com
```

Cheers.

**Comment by rogerwelin** [comment]
Hi @lakuapik and thanks for your kind words. I can see how that would be useful. Addind a `--insecure` flag would be the best option imo.
