### ISSUE TITLE
add support for x509 authentication

### ISSUE THREAD

**Issue by vkuznet** [rogerwelin/cassowary#6]
All our services are behind x509 authentication, could you please add support for it. For instance I provided x509 support for hey tool here https://github.com/vkuznet/hey/tree/x509 via https://github.com/vkuznet/x509proxy

**Comment by rogerwelin** [comment]
Hi @vkuznet, thanks for the interest in the project. Certainly I will consider adding this feature, however there are some planned features that I will add first

**Comment by rogerwelin** [comment]
@vkuznet implemented in release [v0.10.0](https://github.com/rogerwelin/cassowary/releases/tag/v0.10.0) 

Sorry about the extreme delay, but better late then never I suppose :)
